name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Oder der Branch, den du verwendest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git add .
          git commit -m "Automated commit"
          git push
